version: '3.9'
services:
#  backend:
#    build: .
#    ports:
#      - 8000:3000
#    volumes:
#      - .:/app
#    depends_on:
#      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql-5.7.22:/var/lib/mysql
    ports:
      - 3334:3306
  db-2:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: pmtoan
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql-8.0:/var/lib/mysql
    ports:
      - 3333:3306
